platform :ios, '9.0'

target 'Example' do
  use_frameworks!

  pod 'SDWebImage'
  
  pod 'JXCategoryViewExt/DotZoom', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/SubTitle', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/SubTitleImage', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Indicator/Background', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/TitleImage', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Indicator/AlignmentLine', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Badge', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Number', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Dot', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Image', :path => '../../JXCategoryViewExt'
#  pod 'JXCategoryViewExt/RTL', :path => '../../JXCategoryViewExt'

end
