platform :ios, '9.0'

target 'Example' do
  use_frameworks!

  pod 'JXCategoryViewExt/DotZoom', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/Indicator/Background', :path => '../../JXCategoryViewExt'
  pod 'JXCategoryViewExt/TitleImage', :path => '../../JXCategoryViewExt'
#  pod 'JXCategoryViewExt/RTL', :path => '../../JXCategoryViewExt'

end
